version: '3.7'

services:
  web:
    container_name: "web"
    build:
      context: .
      dockerfile: Dockerfile
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/usr/src/code
    ports:
      - 8000:8000
    env_file: code/.env
    stdin_open: true
    tty: true