# Generated by Django 3.2 on 2021-04-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20210424_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='client',
            name='rg',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='ddd',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='number',
            field=models.CharField(max_length=9),
        ),
    ]
